name: Vote CI

on:
  push:
    branches:
      - main
      - Integrity_checks
    paths:
      - 'vote/**'
  pull_request:
    branches:
      - main
      - Integrity_checks
    paths:
      - 'vote/**'

jobs:
  build_vote:
    name: Build Vote Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set IMAGE_VERSION
        id: version
        run: echo "::set-output name=version::voting-vote-${{ github.run_number }}"

      - name: Build Vote Docker Image
        run: |
          # Use the IMAGE_VERSION variable set above
          docker build -t voting-vote:${{ github.run_number }} -f vote/Dockerfile vote/
          
  push_vote:
    name: Push Vote Docker Image
    runs-on: ubuntu-latest
    needs: build_vote 

    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Vote Docker Image
        run: |
          # Use the IMAGE_VERSION variable set in the build_vote step
          docker push voting-vote:${{ github.run_number }}

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
