name: Result CI

on:
  push:
    branches:
      - main
    paths:
      - 'result/**'
  pull_request:
    branches:
      - main
    paths:
      - 'result/**'

jobs:
  build_result:
    name: Build Result Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Result Docker Image
        run: docker build -t voting-app-result:latest -f result/Dockerfile result/

  push_result:
    name: Push Result Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Result Docker Image
        run: docker push voting-app-result:latest

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}