name: Result CI

on:
  push:
    branches:
      - main
    paths:
      - 'result/**'
  pull_request:
    branches:
      - main
    paths:
      - 'result/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_result:
    name: Build Result Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set IMAGE_VERSION
      #   id: version
      #   run: echo "::set-output name=version::voteresult-latest

      - name: Build Result Docker Image
        run: |
          # Use the IMAGE_VERSION variable set above
          docker build -t voteresult:latest -f result/Dockerfile result/

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

  push_result:
    name: Push Result Docker Image
    runs-on: ubuntu-latest
    needs: [build_result]

    steps:
      - name: Wait for Build to Complete
        run: echo "Build is completed. Proceeding with pushing."

      - name: Push Result Docker Image
        run: |
          # Use the IMAGE_VERSION variable set in the build_result step
          docker push voteresult:latest
