name: Result CI

on:
  push:
    branches:
      - main
    paths:
      - 'result/**'
  pull_request:
    branches:
      - main
    paths:
      - 'result/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_result:
    name: Build and push Result Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Result Docker Image
        run: |
          # Use the IMAGE_VERSION variable set above
          docker build -t voting-result:${{ github.run_number }} -f result/Dockerfile result/

      - name: Create Version Tag and Push
        run: |
          # Tag the image with "latest" and push it
          docker tag voting-result:${{ github.run_number }} voting-result:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push voting-result:latest

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  push_result:
    name: Push Result Docker Image
    runs-on: ubuntu-latest
    needs: build_result

    steps:
      - name: Wait for Build to Complete
        run: echo "Build is completed. Proceeding with pushing."

      - name: Push Result Docker Image
        run: |
          # Use the IMAGE_VERSION variable set in the build_result step
          docker push voting-result:${{ github.run_number }}