name: Vote CI

on:
  push:
    branches:
      - main
    paths:
      - 'vote/**'
  pull_request:
    branches:
      - main
    paths:
      - 'vote/**'

jobs:
  build_vote:
    name: Build Vote Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Vote Docker Image
        run: |
          # Use the GitHub Run Number for unique versioning
          VERSION="voting-app-vote:${{ github.run_number }}"
          docker build -t $VERSION -f vote/Dockerfile vote/
          echo "::set-env name=IMAGE_VERSION::$VERSION" # Set the IMAGE_VERSION variable for later use

      # Set the IMAGE_VERSION environment variable for subsequent steps
      - name: Set IMAGE_VERSION
        run: echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

  push_vote:
    name: Push Vote Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Vote Docker Image
        run: |
          # Use the IMAGE_VERSION environment variable set in the previous step
          docker push $IMAGE_VERSION

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}