name: Docker CI

on:
  push:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'
  pull_request:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'

jobs:
  build_vote:
    name: Build Vote Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Vote Docker Image
        run: |
          docker build -t voting-app-image:latest -f vote/Dockerfile vote/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build_result:
    name: Build Result Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Result Docker Image
        run: |
          docker build -t voting-app-result:latest -f result/Dockerfile result/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build_worker:
    name: Build Worker Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Worker Docker Image
        run: |
          docker build -t voting-worker:latest -f worker/Dockerfile worker/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push_images:
    name: Push Docker Images
    runs-on: ubuntu-latest
    needs: [build_vote, build_result, build_worker]
    steps:
      - name: Push Vote Docker Image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push voting-app-image:latest

      - name: Push Result Docker Image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push voting-app-result:latest

      - name: Push Worker Docker Image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push voting-worker:latest
