name: Docker CI

on:
  push:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'
  pull_request:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    name: Build Vote Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set IMAGE_VERSION
        id: version_vote
        run: echo "::set-output name=version::votevote-${{ github.run_number }}"

      - name: Build Vote Docker Image
        run: |
          # Use the IMAGE_VERSION variable set above
          docker build -t votevote:${{ github.run_number }} -f vote/Dockerfile vote/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set IMAGE_VERSION
        id: version_result
        run: echo "::set-output name=version::voteresult-${{ github.run_number }}"

      - name: Build Result Docker Image
        run: |
          # Use the IMAGE_VERSION variable set above
          docker build -t voteresult:${{ github.run_number }} -f result/Dockerfile result/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set IMAGE_VERSION
        id: version_worker
        run: echo "::set-output name=version::voteworker-${{ github.run_number }}"

      - name: Build Worker Docker Image
        run: |
          # Use the IMAGE_VERSION variable set above
          docker build -t voteworker:${{ github.run_number }} -f worker/Dockerfile worker/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Vote Docker Image
        run: |
          # Use the IMAGE_VERSION variable set in the build_vote step
          docker push votevote:${{ github.run_number }}

      - name: Push Result Docker Image
        run: |
          # Use the IMAGE_VERSION variable set in the build_result step
          docker push voteresult:${{ github.run_number }}

      - name: Push Worker Docker Image
        run: |
          # Use the IMAGE_VERSION variable set in the build_worker step
          docker push voteworker:${{ github.run_number }}
