name: Python CI and Docker Build/Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r vote/requirements.txt

      - name: Run tests (or other tasks)
        run: |
          python -m unittest discover

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin https://index.docker.io/v1/
        
      - name: Build Docker Image
        run: docker build -t my-image:latest .
      
      - name: Push Docker Image
        run: docker push my-image:latest
