name: Docker Build and Push

on:
  push:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'
  pull_request:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'

jobs:
  build-and-push:
    name: Build and Push Docker Images

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Push Vote Docker Image
        run: |
          docker buildx create --use
          docker buildx build -t ghcr.io/${{ github.repository_owner }}/example-voting-app-vote:latest -f vote/Dockerfile vote/
          docker push ghcr.io/${{ github.repository_owner }}/example-voting-app-vote:latest

      - name: Build and Push Result Docker Image
        run: |
          docker buildx create --use
          docker buildx build -t ghcr.io/${{ github.repository_owner }}/example-voting-app-result:latest -f result/Dockerfile result/
          docker push ghcr.io/${{ github.repository_owner }}/example-voting-app-result:latest

      - name: Build and Push Worker Docker Image
        run: |
          docker buildx create --use
          docker buildx build -t ghcr.io/${{ github.repository_owner }}/example-voting-app-worker:latest -f worker/Dockerfile worker/
          docker push ghcr.io/${{ github.repository_owner }}/example-voting-app-worker:latest
