name: Docker CI

on:
  push:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'
  pull_request:
    paths:
      - 'vote/**'
      - 'result/**'
      - 'worker/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Vote Docker Image
        run: |
          docker build -t golanm/voting:votevote -f vote/Dockerfile vote/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Result Docker Image
        run: |
          docker build -t golanm/voting:voteresult -f result/Dockerfile result/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Worker Docker Image
        run: |
          docker build -t golanm/voting:voteworker -f worker/Dockerfile worker/
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        run: |
          docker login docker.io -u $DOCKER_USERNAME --password-stdin <<< $DOCKER_PASSWORD

      - name: Debug Docker Info
        run: |
          docker --version
          docker info

      - name: Debug Docker Config
        run: |
          docker --config ~/.docker/config.json --version

      - name: Push Vote Docker Image
        run: |
          docker push golanm/voting:votevote

      - name: Push Result Docker Image
        run: |
          docker push golanm/voting:voteresult

      - name: Push Worker Docker Image
        run: |
          docker push golanm/voting:voteworker
      